RD_1 = 20
RD_2 = 15
RD_3 = 10
RD_4 = 8

DEBUG_MODE = False

SLOPE_AVG_MODE = 111
RECTANGLE_MODE = 222
VEHICLE_RUNNER = 333
IDEAL_PLT_MODE = 999

TEXT_SIZE = 3
TEXT_SPACING = 6
SCALE_FACTOR = 0.6

VEHICLE_BOX_MESH = 1
WHEEL_MESH_F = 3
WHEEL_MESH_B = 4
WHL_BOTTOM_MESH = 5
WHL_CENTER_MESH = 6

WHL_AXLE_MESH_F = 7
WHL_AXLE_MESH_B = 8

VEH_CENTER_MESH = 9

MESH_DIR: dict[int, str] = dict()

MESH_DIR[VEHICLE_BOX_MESH] = 'Vehicle Box Mesh'
MESH_DIR[WHEEL_MESH_F] = 'Wheel Mesh Front Side'
MESH_DIR[WHEEL_MESH_B] = 'Wheel Mesh Back Side'
MESH_DIR[WHL_BOTTOM_MESH] = 'Wheel Bottom Mesh'
MESH_DIR[WHL_CENTER_MESH] = 'Vehicle Box Mesh'
MESH_DIR[WHL_AXLE_MESH_F] = 'Wheel Axle Front'
MESH_DIR[WHL_AXLE_MESH_B] = 'Wheel Axle Back'
MESH_DIR[VEH_CENTER_MESH] = 'Vehicle Center Mesh'

